spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /actuator/health
        healthCheckInterval: 20s
        instanceId: ${spring.application.name}:${random.value}
    gateway:
      routes:
        # =====================================
        # routes to be listed here
        # Java routing can be used as well, but to change it - recompilation and restart would be needed
        # Properties can be changed on the fly

server:
  port: 8765
  error:
    whitelabel:
      enabled: true

logging:
  level:
    org.springframework.web: INFO

# Secret to generate tokens, used in both auth service and in gateway
auth-service:
  jwtSecret: a3ZzApRSDQF5E9cH3JFV1LNBzOtQEiv6OumGJudd3Ao=
