version: '3.4'

networks:
  lan:

services:
  consul:
    image: consul:latest
    hostname: localhost
    networks:
      - lan
    ports:
      - "8500:8500"
  ui:
    container_name: ui-service
    image: ui-service
    build:
      context: ./ui
      dockerfile: Dockerfile
    restart: always
    networks:
      - lan
    ports:
      - "8080:8080"
