name: charts CI
on:
  pull_request:
    paths:
      - charts/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Build
        run: ./charts/gradlew build
      - name: Test
        run: ../charts/gradlew test
